### ISSUE TITLE
Email privacy issue

### ISSUE THREAD

**Issue by d-r-e** [JaeSeoKim/badge42#10]
The widget is great, but I would love to be able to hide the email so that spam bots can't find it. Also, as a suggestion, it would be really useful to show expertises as a list, or the number of achievements unlocked. Thanks for your work!

**Comment by JaeSeoKim** [comment]
Thank you for your very good opinion!
First of all, I'll quickly add a private option for email!

**Comment by d-r-e** [comment]
So quick 💯🥇

**Comment by JaeSeoKim** [comment]
@all-contributors please add @d-r-e for ideas
