### ISSUE TITLE
Unable to generate badge for my profile

### ISSUE THREAD

**Issue by pde-bakk** [JaeSeoKim/badge42#3]
Couldn't generate a badge for my own profile. Maybe its because I'm not part of 42Seoul (I'm from 42Amsterdam aka Codam) ?

I attached a screenshot of the error.

![image](https://user-images.githubusercontent.com/36886300/97559097-4ae63600-19dd-11eb-9abb-c458e46b9794.png)

**Comment by JaeSeoKim** [comment]
Hi! I'm so glad to talk with you! I'm little bit busy right now, but I'll check it out ASAP, and send some messages to you. thanks friends!

**Comment by JaeSeoKim** [comment]
![image](https://user-images.githubusercontent.com/48559454/97778354-0237a400-1bba-11eb-8307-f24349a23ae9.png)

Solved the problem and it's going to work now!

**Comment by pde-bakk** [comment]
Awesome, thanks man!
감사합니다!

**Comment by JaeSeoKim** [comment]
@all-contributors please add @pde-bakk for bug
