### ISSUE TITLE
"Succes"

### ISSUE THREAD

**Issue by olesgedz** [JaeSeoKim/badge42#32]
<img width="444" alt="Screen Shot 2021-01-03 at 4 46 00 PM" src="https://user-images.githubusercontent.com/8808075/103480084-36f6f000-4de3-11eb-986f-4749be7d1caa.png">
Succes

**Comment by JaeSeoKim** [comment]
😱Whoops...!!

I will fix typo quickly!! Thanks!!!

**Comment by JaeSeoKim** [comment]
@all-contributors please add @olesgedz  for bug
