### ISSUE TITLE
Secondary campus displayed instead of primary

### ISSUE THREAD

**Issue by jkctech** [JaeSeoKim/badge42#36]
When used on my username, my secondary campus is displayed on the badge instead of my primary one:

To reproduce:
https://badge42.herokuapp.com/api/stats/jkoopman

Proof:
My primary campus is Codam (Amsterdam) But I am displayed as 42 Wolfsburg (In Wolfsburg)
![bcbcd51cba3632f1704d498dad8db755](https://user-images.githubusercontent.com/2072890/108493675-e100dd80-72a6-11eb-99d8-58c812d7b702.png)
![a7e4354d188fa2f2e617c3ffd53ca22d](https://user-images.githubusercontent.com/2072890/108493684-e3fbce00-72a6-11eb-86b5-ec625b08ce5c.png)

**Comment by JaeSeoKim** [comment]
@all-contributors please add @jkctech  for bug
