### ISSUE TITLE
Unable to generate 42cursus badge

### ISSUE THREAD

**Issue by aabajyan** [JaeSeoKim/badge42#38]
This bug seems to occur only for 42yerevan users and only if it tries to generate a 42cursus badge.
C Piscine:
![C Piscine test](https://badge42.herokuapp.com/api/stats/aabajyan?cursus=C%20Piscine&privacyEmail=true)

42cursus:
![C Piscine test](https://badge42.herokuapp.com/api/stats/aabajyan?privacyEmail=true)

**Comment by JaeSeoKim** [comment]
@all-contributors please add @aabajyan for code, bug
