### ISSUE TITLE
Error on multiple badge in github markdown

### ISSUE THREAD

**Issue by cos18** [JaeSeoKim/badge42#4]
When using multiple badge, it can't render and throw error like this.

[![holee's 42 stats](https://badge42.herokuapp.com/api/stats/holee)](https://profile.intra.42.fr/users/holee)
[![sunpark's 42 stats](https://badge42.herokuapp.com/api/stats/sunpark)](https://profile.intra.42.fr/users/sunpark)
[![jachoi's 42 stats](https://badge42.herokuapp.com/api/stats/jachoi)](https://profile.intra.42.fr/users/jachoi)

[Another Example](https://github.com/42js/you-dont-know-js-yet/blob/8cb3aa75f827e5d4f7769cbc88d8f0f7c2bba61f/README.md)

**Comment by JaeSeoKim** [comment]
```JS
    ctx.res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    ctx.res.setHeader("Pragma", "no-cache");
    ctx.res.setHeader("Expires", "0");
```

에러시 위의 헤더를 같이 전송함으로 브라우저에서 캐쉬를 못하도록 함

새로고침시 새로운 데이터를 재요청 하여 가져오는 것이 가능하게 됨

---

✅ TODO

- [ ] API 요청 제한 해제 문의 하기
