### ISSUE TITLE
Addition of certification procedures to satisfy the EU GDPR policy.

### ISSUE THREAD

**Issue by JaeSeoKim** [JaeSeoKim/badge42#66]
- #67

**Comment by GlaceCoding** [comment]
We should not be able to see a card of user which not login a first time and give this consent, also the student can remove this consent at everytime :)

And privacyEmail / privacyName should be false by default and set true only by the concerned student.

**Comment by GlaceCoding** [comment]
Also if an user is BH can he login to remove this consent? but maybe he would like to keep this card or not 🤔

**Comment by sanvit** [comment]
@GlaceCoding afaik as long as the user isn't anonymized, the user should be able to receive their school domain email, so you can verify with that I guess.
If the user gets anonymized, the API wouldn't be able to access their data anyways, so I think it won't be a problem

**Comment by HamaBarhamou** [comment]
What if the student is not 42?

**Comment by JaeSeoKim** [comment]
I’m sorry for the delay. There was a Covid issue in the middle, so I couldn’t develop it.
Currently, along with the basic StatsBadge, 42, GitHub login and account deletion functions have been implemented.
I would appreciate it if you could tell me what to improve along with the additional functions you need.
https://badge42.vercel.app/
jaeskim’s stats badge: https://badge42.vercel.app/api/v2/stats/cl0yx1v0j0158ns5shlllmdvb?cursusId=21

**Comment by JaeSeoKim** [comment]
> What if the student is not 42?

It is basically a service for 42 students, so it is not subject to service.

**Comment by GlaceCoding** [comment]
> I’m sorry for the delay. There was a Covid issue in the middle, so I couldn’t develop it. Currently, along with the basic StatsBadge, 42, GitHub login and account deletion functions have been implemented. I would appreciate it if you could tell me what to improve along with the additional functions you need. https://badge42.vercel.app/ jaeskim’s stats badge: https://badge42.vercel.app/api/v2/stats/cl0yx1v0j0158ns5shlllmdvb?cursusId=21

Don't be sorry, your work is great ! 

I did some UI comment in the PR https://github.com/JaeSeoKim/badge42/pull/67#issuecomment-1073192751

**Comment by dabel-co** [comment]
> I’m sorry for the delay. There was a Covid issue in the middle, so I couldn’t develop it. Currently, along with the basic StatsBadge, 42, GitHub login and account deletion functions have been implemented. I would appreciate it if you could tell me what to improve along with the additional functions you need. https://badge42.vercel.app/ jaeskim’s stats badge: https://badge42.vercel.app/api/v2/stats/cl0yx1v0j0158ns5shlllmdvb?cursusId=21

Having a way to display the score of certain projects ( the old [42Project Score] ) would be really neat. Thank you for making this GDPR friendly!
