### ISSUE TITLE
Internal server error and wrong info in cursus

### ISSUE THREAD

**Issue by Nimon77** [JaeSeoKim/badge42#69]
Hello, I have an internal server error when I try to access my piscine stats badge at this [url](https://badge42.vercel.app/api/v2/stats/cl1760y9m000609l6a99op4na?cursusId=9)
and the infos displayed in the 42cursus badge are not good, the lvl is not right and the coalition are the one from my piscine 🥲
<img width="522" alt="image" src="https://user-images.githubusercontent.com/11821952/160219345-a8e09ecd-4efe-4255-9a92-c694dcad1724.png">

Thanks !

**Comment by JaeSeoKim** [comment]
May I know the ID of the account that is in error?

<img width="707" alt="image" src="https://user-images.githubusercontent.com/48559454/160224177-111dc901-2682-4f45-a46d-7f88d7d4a9c0.png">

**Comment by JaeSeoKim** [comment]
In case of piscine in 42Seoul, I didn't think about it because there was no coalition.
I will add a selection function for coalition.

**Comment by Nimon77** [comment]
This is my account ID : cl1760y9m000609l6a99op4na

**Comment by JaeSeoKim** [comment]
https://github.com/JaeSeoKim/badge42/blob/7cd3225773dc848eaf4f5fd0bdb7bf2ff74c77df/components/badge/Stats/Stats.tsx#L55

In the case of Level, it was a problem because I did not change the part I wrote as a constant for the test. 🥲

**Comment by JaeSeoKim** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/48559454/160265101-4c6109c5-cff2-4fed-9fa6-6e45b36a9d66.png">

First, I resolved Internal server error.

**Comment by Nimon77** [comment]
Nice ! Thanks !

**Comment by JaeSeoKim** [comment]
sorry for too late... added the coalition selection function

**Comment by Nimon77** [comment]
Thanks, It seem not to work but maybe it's a CDN problem ? https://badge42.vercel.app/api/v2/stats/cl1760y9m000609l6a99op4na?cursusId=21&coalitionId=46
![Screenshot from 2022-04-04 15-33-25](https://user-images.githubusercontent.com/11821952/161555452-46fdb635-d535-4944-81fb-6ab7cf1023a4.png)

**Comment by JaeSeoKim** [comment]
Oops... It's working incorrectly because of the bracket issue. I fixed it.

**Comment by JaeSeoKim** [comment]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/48559454/161565704-cdf86e7d-293b-4e98-b3d7-b44e976f5e09.png">

**Comment by JaeSeoKim** [comment]
@all-contributors please add @Nimon77  for bug

**Comment by Nimon77** [comment]
Thank you !!
Now all is good for me ;)
