### ISSUE TITLE
experience bar is a bit overflowing

### ISSUE THREAD

**Issue by lejulien-42** [JaeSeoKim/badge42#77]
I am level 7,99 and the experience bar is bigger than the badge box
![Screenshot 2022-04-07 at 9 21 14 PM](https://user-images.githubusercontent.com/57351742/162280544-d7e732ad-d292-46c5-bb3a-89458e3d46f1.png)

**Comment by JaeSeoKim** [comment]
![image](https://user-images.githubusercontent.com/48559454/162569256-b6e1cebb-c68e-4346-af18-21cf47919d19.png)
This error has been resolved, but changes can take more than 12 hours depending on the CDN Cache policy.

**Comment by lejulien-42** [comment]
Nice well-done ^^
