### ISSUE TITLE
App doesn't work for me

### ISSUE THREAD

**Issue by hheimerd** [JaeSeoKim/badge42#79]
I log in using intra, copy-paste md, but I have a 500 error
generated [link](https://badge42.vercel.app/api/v2/cl4o6whdt005009l8cywxq525/stats?cursusId=21&coalitionId=81) (hheimerd)

**Comment by JaeSeoKim** [comment]
Unfortunately, I will join the army as of the 27th due to the military service duty of the Republic of Korea, so I don't have time to solve this problem…

If you solve this problem yourself and send me a PR, it will take some time, but I will merge it after review.

**Comment by JaeSeoKim** [comment]
I solved it because it was a simple url encode problem.

![sample](https://badge42.vercel.app/api/v2/cl4o6whdt005009l8cywxq525/stats?cursusId=21&coalitionId=81)
