### ISSUE TITLE
the image is gone(

### ISSUE THREAD

**Issue by Mechnuna** [JaeSeoKim/badge42#80]
Internal Server Error
https://badge42.vercel.app/api/v2/cl2rh9zht001109l643vtx5wr/stats?cursusId=21&coalitionId=91

**Comment by JaeSeoKim** [comment]
Now you can use this!

![preview](https://badge42.vercel.app/api/v2/cl2rh9zht001109l643vtx5wr/stats?cursusId=21&coalitionId=91)
