### ISSUE TITLE
Error in Exp precision

### ISSUE THREAD

**Issue by cos18** [JaeSeoKim/badge42#9]
There is an error in exp number.

[![sunpark's 42 stats](https://badge42.herokuapp.com/api/stats/sunpark)](https://profile.intra.42.fr/users/sunpark)

<br><br>

Below I add img of my screenshot if others didn't notice this error.
<img width="516" alt="Screen Shot 2020-11-11 at 11 41 01 PM" src="https://user-images.githubusercontent.com/33975709/98825141-8110c480-2477-11eb-990c-881b529bcef6.png">

**Comment by JaeSeoKim** [comment]
@all-contributors please add @cos18  for bug
